name: CD

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    - name: Azure key vault login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: Fetch secrets from key vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "dipvp"
        secrets: 'NPM-TOKEN'
      id: fetchSecrets
    
    - name: Write npmrc
      run: |
        echo "@equinor-internal:registry=https://npm.equinor.com" > $HOME/.npmrc
        echo //npm.equinor.com/:_authToken=${{ steps.fetchSecrets.outputs.NPM-TOKEN }} >> $HOME/.npmrc
        yarn config set registry https://npm.equinor.com

    - name: Install dependencies
      run: yarn

    - name: Publish
      run: | 
        yarn publish --access=public

    - name: Build gh-pages
      run: yarn predeploy

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
